name: "FRITZ!Portal"
version: "1.3.4"
slug: "fritz-portal"
description: "FRITZ!Box Dashboard für Home Assistant"
url: "https://github.com/jayjojayson/FRITZ-Portal"
arch:
  - aarch64
  - amd64
  - armhf
init: false
startup: application
boot: auto
ingress: true
ingress_port: 3003
ingress_stream: false
panel_icon: "mdi:router-wireless"
panel_title: "FRITZ!Portal"
panel_admin: true
hassio_api: true
homeassistant_api: true
host_network: true
ports:
  3003/tcp: null
ports_description:
  3003/tcp: "FRITZ!Portal Web UI"
options:
  fritzbox_host: "fritz.box"
  fritzbox_user: ""
  fritzbox_password: ""
  ha_sensors: false
  ha_sensors_interval: 60
  ha_sensors_traffic_interval: 300
schema:
  fritzbox_host: "str"
  fritzbox_user: "str"
  fritzbox_password: "str"
  ha_sensors: bool
  ha_sensors_interval: int
  ha_sensors_traffic_interval: int
